[template]
src = "production.tmpl"
dest = "../config/default.json"
keys = [
    "/configuration/logger/level",
    "/configuration/swagger/jsonPath",
    "/configuration/swagger/uiPath",
    "/configuration/swagger/port",
    "/configuration/elastic/node",
    "/configuration/elastic/request/from",
    "/configuration/elastic/request/size"
]
