openapi: 3.0.1
info:
  title: Common Storage Service
  description: An Elasticsearch generic service for common usecases.
  version: 1.0.0
servers:
  - url: http://localhost:80/
paths:
  /indexes:
    get:
      tags:
        - indexes
      summary: Get all indexes from the database.
      responses:
        200:
          description: All indexes.
        404:
          description: No indexes in the database.
        400:
          description: Invalid request, could not retrieve indexes.
    post:
      tags:
        - indexes
      summary: Create a new index and returns it.
      requestBody:
        description: The properties that need to be sent.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/indexes'
        required: true
      responses:
        200:
          description: Returns the created index.
        400:
          description: Invalid request, could not create index.
          
  /indexes/{name}:
    get:
      tags:
        - indexes
      summary: Get a specific index.
      parameters: 
      -  $ref: '#/components/parameters/nameParameter'
      responses:
        200:
          description: Information about the index.
        404:
          description: Index not found.
        400: 
          description: Invalid request, could not retrieve index.
    delete:
      tags:
        - indexes
      summary: Delete the specific index and returns it.
      parameters: 
      - name: name
        in: path
        description: The name of the required index.
        required: true
        schema:
          type: string
      responses:
        200:
          description: Information about the deleted index.
        404:
          description: Index not found, did not delete.
        400: 
          description: Invalid request, could not retrieve index.        
          
  /indexes/{name}/document:
   get:
      tags:
        - indexes
      summary: Get documents from specific index.
      parameters: 
      -  $ref: '#/components/parameters/nameParameter'
      - in: query
        description: Fields that are the criteria - document must match the fields supplied. If empty - returns all documents.
        name: params
        required: false
        schema:
          type: object
          additionalProperties: {}
        example:
          _id: 123456
      - in: query
        description: The offset to start the searching from. Default is 0.
        name: from
        required: false
        schema:
          type: number
        example:
          50
      - in: query
        description: Size of reslts to return from the server. Default is 10.
        name: size
        required: false
        schema:
          type: number
        example:
          4       
      responses:
        200:
          description: Returns all documents that met the criteria.
        404:
          description: Index not found.
        400: 
          description: Invalid request, could not retrieve index.     
   post:
    tags:
      - indexes 
    summary: Create a new document in the index.
    requestBody:
        description: Example of request body input
        required: true  
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/documents'
    parameters:
    - $ref: '#/components/parameters/nameParameter'
    responses:
      200:
        description: Creates the document and returns it.
      404:
        description: Index not found, did not create document.
      400: 
          description: Invalid request, could not retrieve index.    
          
   put:
    tags:
      - indexes 
    summary: Request processed - response tells if it updated sucessfully or did not update (because the document does not exist)
    requestBody:
        description: Example of request body input
        required: true  
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/documents'
    parameters:
    - $ref: '#/components/parameters/nameParameter'
    - in: query
      name: params
      required: false
      schema:
        type: object
        additionalProperties: {}
      example:
        customID: 123
    responses:
      200:
        description: Updates the document and returns data about the transaction.
      404:
        description: Index not found, did not update document.
      400: 
          description: Invalid request, could not retrieve index.           

  /indexes/{name}/document/{documentId}:
    get:
      tags:
      - indexes
      summary: Get a document by its unique ID.
      parameters:
      - $ref: '#/components/parameters/nameParameter'
      - name: documentId
        in: path
        required: true
        description: ID of the document to delete.
        schema:
          type: string      
      responses:
        200:
          description: Returns the document.
        404:
          description: Document not fond.
        400: 
            description: Invalid request, could not retrieve index.      

    delete:
      tags:
      - indexes
      summary: Deletes a specific document.
      parameters:
      - $ref: '#/components/parameters/nameParameter'
      - name: documentId
        in: path
        required: true
        description: ID of the document to delete.
        schema:
          type: string
      responses:
        200:
          description: Creates the document and returns it.
        404:
          description: Index not found, did not create document.
        400: 
            description: Invalid request, could not retrieve index.      
    
components:
  parameters:
    nameParameter:
      name: name
      in: path
      description: Name of the index
      required: true
      schema:
        type: string
  schemas:
    indexes:
      properties:
        index:
          type: string
      example:
        index: test
    documents:
      properties:
        params:
          type: object
      example:
        params: { firstName: "Moshe", lastName: "Shalom" }  
