openapi: 3.0.1
info:
  title: service-name
  description: basic template for map colonies service
  version: 1.0.0
servers:
  - url: http://localhost:1337
paths:
  /indexes:
    get:
      tags:
        - indexes
      summary: Get all indexes from the db. Use query parameters to select a specific one.
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/indexes"
        400:
          description: BAD_REQUEST  
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/indexes"
components:
  parameters:
    idParam:
      name: id
      in: query
      description: id of requested item
      required: true
      schema:
        type: string
        format: uuid
  schemas:
    indexes:
      properties:
        index:
          type: string
      example:
        matches: [{"_index": "test"}]
